# Generated by Django 5.2.4 on 2025-08-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCode', models.CharField(max_length=50, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCode', models.CharField(max_length=255)),
                ('clientName', models.CharField(max_length=255)),
                ('clientCountry', models.CharField(max_length=100)),
                ('launchDate', models.DateField()),
                ('reinsurer', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(max_length=100)),
                ('freqBordereau', models.CharField(max_length=100)),
                ('freqReport', models.CharField(max_length=100)),
                ('accountingPrinciple', models.CharField(max_length=100)),
                ('primaryCurrency', models.CharField(max_length=10)),
                ('secondaryCurrency', models.CharField(blank=True, max_length=10, null=True)),
                ('taxProduct', models.CharField(blank=True, max_length=100, null=True)),
                ('monthlyReport', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to='SOR.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productCatalogueId', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('productType', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='SOR.client')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
                ('Reinsurance_Premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Risk_Premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BD_Fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('gross_premium', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('fronting_fee', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('brokerage', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_rates', to='SOR.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_from', models.IntegerField(blank=True, null=True)),
                ('number_to', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='SOR.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveDate', models.DateField()),
                ('effectiveTo', models.DateField(blank=True, null=True)),
                ('retention', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_info', to='SOR.client')),
            ],
        ),
    ]
