# Generated by Django 5.2.4 on 2025-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='house',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
