# Generated by Django 5.2.4 on 2025-07-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOR', '0002_otprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
