# Generated by Django 5.2.4 on 2025-08-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOR', '0003_delete_otprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiuminfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='productID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='SOR.client'),
        ),
        migrations.AlterField(
            model_name='retentioninfo',
            name='retention',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_from', models.IntegerField(blank=True, null=True)),
                ('number_to', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='SOR.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
                ('Reinsurance_Premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Risk_Premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BD_Fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('gross_premium', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('fronting_fee', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('brokerage', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_rates', to='SOR.productinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountInfo',
        ),
        migrations.DeleteModel(
            name='PremiumInfo',
        ),
    ]
